#!/usr/bin/env bash
# post-agent-commit.sh — Runs after a Junie agent exits.
# Commits, pushes, and opens a PR for the agent's worktree.
#
# Usage: post-agent-commit.sh <worktree-path> <branch-name> <agent-label>
#
# Requires: git, gh (GitHub CLI, authenticated)

set -euo pipefail

WORKTREE="$1"
BRANCH="$2"
LABEL="$3"

cd "$WORKTREE"

# Check if there are any changes to commit
if git diff --quiet HEAD && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "[$LABEL] No changes to commit."
  exit 0
fi

echo "[$LABEL] Committing changes..."
git add -A
git commit -m "feat($LABEL): auto-commit agent work" \
  --trailer "Co-authored-by: Junie <junie@jetbrains.com>" || {
  echo "[$LABEL] Nothing to commit (maybe already committed)."
}

echo "[$LABEL] Pulling latest from origin/$BRANCH (rebase)..."
git pull --rebase origin "$BRANCH" 2>&1 || {
  echo "[$LABEL] Pull --rebase failed, attempting to continue..."
  git rebase --abort 2>/dev/null || true
  # If rebase fails, force-push as last resort
  echo "[$LABEL] Force-pushing to origin/$BRANCH..."
  git push --force-with-lease origin "$BRANCH" 2>&1 || {
    echo "[$LABEL] Force-push also failed."
    exit 1
  }
  echo "[$LABEL] Force-push succeeded."
  # skip normal push below
  PUSHED=1
}

if [ "${PUSHED:-}" != "1" ]; then
  echo "[$LABEL] Pushing to origin/$BRANCH..."
  git push origin "$BRANCH" 2>&1 || {
    echo "[$LABEL] Normal push failed, trying force-with-lease..."
    git push --force-with-lease origin "$BRANCH" 2>&1 || {
      echo "[$LABEL] Push failed entirely."
      exit 1
    }
  }
fi

# Create PR if one doesn't already exist for this branch
EXISTING_PR=$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number' 2>/dev/null || true)
if [ -n "$EXISTING_PR" ] && [ "$EXISTING_PR" != "null" ]; then
  echo "[$LABEL] PR #$EXISTING_PR already open for $BRANCH — skipping PR creation."
else
  echo "[$LABEL] Creating pull request..."
  gh pr create \
    --base main \
    --head "$BRANCH" \
    --title "feat: $LABEL agent work" \
    --body "Auto-generated by swarm agent ($LABEL). Committed and pushed automatically after agent task completion." \
    2>&1 || {
    echo "[$LABEL] PR creation failed (gh CLI may not be authenticated)."
  }
fi

echo "[$LABEL] Post-completion done."
